root: true
extends:
  - eslint-config-mlauffer-nodejs
  - plugin:jsdoc/recommended-typescript
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins:
- '@typescript-eslint'
rules:
  jsdoc/require-param: off
  jsdoc/require-returns: off
